permissions:
  BETTER_BONEMEAL:
    name: "Vylepšená Kostní Moučka"
    lore: "Bonemeal který se dá použít na Cactus a Sugar Cane"
    permission: "aeterum.demeter.bonemeal"
    custom_id: 60001
    material: "BONE_MEAL"
    recipe:
      - AIR:AMETHYST_SHARD:AIR
      - AMETHYST_SHARD:BONE_MEAL:AMETHYST_SHARD
      - AIR:AMETHYST_SHARD:AIR
  GROWTH_POTION:
    name: "Lektvar Růstu"
    lore: "Lektvar který urychlý růst rostlin v okolí hráče"
    permission: "aeterum.demeter.growth_potion"
    custom_id: 60002
    recipe:
      - AIR:BETTER_BONEMEAL:AIR
      - BETTER_BONEMEAL:GLASS:BETTER_BONEMEAL
      - AIR:BETTER_BONEMEAL:AIR
  HOE_OF_THE_HARVEST:
    name: "Kosa Úrody"
    lore: "Jestli-že někdo vý jak farmařit tak jsi to ty."
    permission: "aeterum.demeter.hoe"
    custom_id: 60003
  FLOWER_HORSE_TAME:
    name: "Sladké Jablko"
    lore: "Jablko kterým Demeter může ochočit svého koňe"
    permission: "aeterum.demeter.horse_tame"
    custom_id: 60004
  FLOWER_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.demeter.horse_ability"
  DEMETER_GUI:
    name: "GUI"
    permission: "aeterum.demeter.gui"
  PARTY_ATMOSPHERE:
    name: "Party Atmosféra"
    lore: Let's Party!!!
    permission: "aeterum.dionysus.party_atmosphere"
    custom_id: 60013
  PARTY_BALL:
    name: "Party Koule"
    lore: "Pozor na výbuch"
    permission: "aeterum.dionysus.party_ball"
    custom_id: 60012
  RANDOM_EFFECT_POTION:
    name: "Záhadný Nápoj"
    lore: "Kdo vý co se může stát"
    permission: "aeterum.dionysus.random_effect_potion"
    custom_id: 60014
  DRUNK_HORSE_TAME:
    name: "Fermentované Jablko"
    lore: "Jablko kterým Dionysus může ochočit svého koňe"
    permission: "aeterum.dionysus.horse_tame"
    custom_id: 60006
  DRUNK_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.dionysus.horse_ability"
  DIONYSUS_GUI:
    name: "GUI"
    permission: "aeterum.dionysus.gui"
  DARKNESS_POTION:
    name: "Temný Lektvar"
    lore: "Oslep své nepřátele"
    permission: "aeterum.hades.darkness_potion"
    custom_id: 60016
  DARK_PEARL:
    name: "Temná Perla"
    lore: "Prostě Ender Pearl. Možná trochu lepší."
    permission: "aeterum.hades.dark_pearl"
    custom_id: 60017
  DARK_PORTAL:
    name: "Temný Portál"
    lore: "Kde se objevíš?"
    permission: "aeterum.hades.portal"
    custom_id: 60018
  ZOMBIE_HORSE_TAME:
    name: "Otrávené Jablko"
    lore: "Jablko kterým Hades může ochočit svého koňe"
    permission: "aeterum.hades.horse_tame"
    custom_id: 60005
  ZOMBIE_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.hades.horse_ability"
  HADES_COMMAND:
    name: "Nightvision"
    permission: "aeterum.hades.command"
  HADES_GUI:
    name: "GUI"
    permission: "aeterum.hades.gui"
  FLYING_ITEM:
    name: "Nekonečná Raketka"
    lore: "Málo raketek? Použij toto."
    permission: "aeterum.hermes.flying_item"
    custom_id: 60019
  MESSENGER_PACK:
    name: "Poštovní Brašna"
    lore: "Bůh zpráv potřebuje pořádnou brašnu"
    permission: "aeterum.hermes.messenger_pack"
    custom_id: 60020
  SPEED_BOOTS:
    name: "Rychlé botky"
    lore: "Tyhle botky vypadají rychle. Nezakopni."
    permission: "aeterum.hermes.speed_boots"
    custom_id: 60021
  SPEED_HORSE_TAME:
    name: "Rychlé Jablko"
    lore: "Jablko kterým Hermes může ochočit svého koňe"
    permission: "aeterum.hermes.horse_tame"
    custom_id: 60007
  SPEED_HORSE_ABILITY:
    name: "Lektvar Rychlích Kopit"
    lore: "Sedni na svého koně, napij se a drž se"
    permission: "aeterum.hermes.horse_ability"
    custom_id: 60008
  HERMES_GUI:
    name: "GUI"
    permission: "aeterum.hermes.gui"
  SEA_HORSE_TAME:
    name: "Slané Jablko"
    lore: "Jablko kterým Poseidon může ochočit svého koňe"
    permission: "aeterum.poseidon.horse_tame"
    custom_id: 60009
  SEA_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.poseidon.horse_ability"
  WATER_BREATHING_CROWN:
    name: "Mořská Koruna"
    lore: "Pomáhá dýchat pod vodou."
    permission: "aeterum.poseidon.crown"
    custom_id: 60023
  BETTER_TRIDENT:
    name: "Královský Trojzubec"
    lore: "Zbraň hodná krále moří"
    permission: "aeterum.poseidon.trident"
    custom_id: 60022
  POSEIDON_COMMAND:
    name: "Dolphingrace"
    permission: "aeterum.poseidon.command"
  POSEIDON_GUI:
    name: "GUI"
    permission: "aeterum.poseidon.gui"
  PEGASUS_HORSE_TAME:
    name: "Levitující Jablko"
    lore: "Jablko kterým Zeus může ochočit svého koňe"
    permission: "aeterum.zeus.horse_tame"
    custom_id: 60010
  PEGASUS_HORSE_ABILITY:
    name: "Lektvar Levitujících Kopit"
    lore: "Napij se když si na svém koni"
    permission: "aeterum.zeus.horse_ability"
    custom_id: 60011
  BREEDING_ITEM:
    name: "Afrodisiakum"
    lore: "Nakrm zvíře"
    permission: "aeterum.zeus.breeding_item"
    custom_id: 60024
  LIGHTNING_SPEAR:
    name: "Blesk"
    lore: "Zbraň hodná hrále Olympu"
    permission: "aeterum.zeus.lightning_spear"
    custom_id: 60025
  WEATHER_CHANGER:
    name: "Lektvar Bouře"
    lore: "Moc slunečno? Tohle by mohlo být řešení"
    permission: "aeterum.zeus.weather_changer"
    custom_id: 60026
  ZEUS_GUI:
    name: "GUI"
    permission: "aeterum.zeus.gui"
  RANDOMIZER:
    name: "Lopatka"
    permission: "aeterum.trowel.use"
    custom_id: 60015
    recipe:
      - REDSTONE:ENDER_PEARL:REDSTONE
      - IRON_INGOT:ELYTRA:IRON_INGOT
      - IRON_INGOT:REDSTONE:IRON_INGOT