permissions:
  BETTER_BONEMEAL:
    name: "Vylepšená Kostní Moučka"
    lore: "Bonemeal který se dá použít na Cactus a Sugar Cane"
    permission: "aeterum.demeter.bonemeal"
    custom_id: 60001
    material: "BONE_MEAL"
    recipe:
      - AIR:AMETHYST_SHARD:AIR
      - AMETHYST_SHARD:BONE_MEAL:AMETHYST_SHARD
      - AIR:AMETHYST_SHARD:AIR
  GROWTH_POTION:
    name: "Lektvar Růstu"
    lore: "Lektvar který urychlý růst rostlin v okolí hráče"
    permission: "aeterum.demeter.growth_potion"
    custom_id: 60002
    material: "POTION"
    recipe_potion: regeneration
    color:
      red: 63
      green: 206
      blue: 130
    recipe:
      - AIR:BETTER_BONEMEAL:AIR
      - BETTER_BONEMEAL:POTION:BETTER_BONEMEAL
      - AIR:BETTER_BONEMEAL:AIR
  HOE_OF_THE_HARVEST:
    name: "Kosa Úrody"
    lore: "Jestli-že někdo vý jak farmařit tak jsi to ty."
    permission: "aeterum.demeter.hoe"
    custom_id: 60003
    material: "NETHERITE_HOE"
    recipe:
      - GOLD_INGOT:WHEAT:GOLD_INGOT
      - DIAMOND:NETHERITE_HOE:DIAMOND
      - AIR:EMERALD:AIR
  FLOWER_HORSE_TAME:
    name: "Démétéřin Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.demeter.horse_tame"
    custom_id: 60004
    material: "GOAT_HORN"
    recipe:
      - AIR:OXEYE_DAISY:AIR
      - OXEYE_DAISY:GOLDEN_APPLE:OXEYE_DAISY
      - AIR:OXEYE_DAISY:AIR
  FLOWER_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.demeter.horse_ability"
  DEMETER_GUI:
    name: "GUI"
    permission: "aeterum.demeter.gui"
  PARTY_ATMOSPHERE:
    name: "Party Atmosféra"
    lore: Let's Party!!!
    permission: "aeterum.dionysus.party_atmosphere"
    custom_id: 60013
    material: "POTION"
    color:
      red: 255
      green: 185
      blue: 54
    recipe:
      - GLOWSTONE_DUST:GLASS_BOTTLE:GLOWSTONE_DUST
      - HONEY_BOTTLE:GOLDEN_APPLE:HONEY_BOTTLE
      - AIR:AIR:AIR
  PARTY_BALL:
    name: "Party Koule"
    lore: "Pozor na výbuch"
    permission: "aeterum.dionysus.party_ball"
    custom_id: 60012
    material: "SNOWBALL"
    recipe:
      - GUNPOWDER:GLOWSTONE_DUST:GUNPOWDER
      - GLOWSTONE_DUST:SLIME_BALL:GLOWSTONE_DUST
      - AIR:FIRE_CHARGE:AIR
  RANDOM_EFFECT_POTION:
    name: "Záhadný Nápoj"
    lore: "Kdo vý co se může stát"
    permission: "aeterum.dionysus.random_effect_potion"
    custom_id: 60014
    material: "POTION"
    color:
      red: 43
      green: 158
      blue: 54
    recipe:
      - RABBIT_FOOT:GOLDEN_CARROT:GHAST_TEAR
      - FERMENTED_SPIDER_EYE:GLASS_BOTTLE:PHANTOM_MEMBRANE
      - AIR:GLOWSTONE_DUST:AIR
  DRUNK_HORSE_TAME:
    name: "Dionýsův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.dionysus.horse_tame"
    custom_id: 60006
    material: "GOAT_HORN"
    recipe:
      - AIR:RANDOM_EFFECT_POTION:AIR
      - RANDOM_EFFECT_POTION:GOLDEN_APPLE:RANDOM_EFFECT_POTION
      - AIR:RANDOM_EFFECT_POTION:AIR
  DRUNK_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.dionysus.horse_ability"
  DIONYSUS_GUI:
    name: "GUI"
    permission: "aeterum.dionysus.gui"
  DARKNESS_POTION:
    name: "Temný Lektvar"
    lore: "Oslep své nepřátele"
    permission: "aeterum.hades.darkness_potion"
    custom_id: 60016
    material: "POTION"
    color:
      red: 255
      green: 30
      blue: 1
    recipe:
      - AIR:BLACK_DYE:AIR
      - WITHER_ROSE:PHANTOM_MEMBRANE:WITHER_ROSE
      - AIR:FERMENTED_SPIDER_EYE:AIR
  DARK_PEARL:
    name: "Temná Perla"
    lore: "Prostě Ender Pearl. Možná trochu lepší."
    permission: "aeterum.hades.dark_pearl"
    custom_id: 60017
    material: "ENDER_PEARL"
    recipe:
      - AIR:PHANTOM_MEMBRANE:AIR
      - PHANTOM_MEMBRANE:ENDER_PEARL:PHANTOM_MEMBRANE
      - AIR:PHANTOM_MEMBRANE:AIR
  DARK_PORTAL:
    name: "Temný Portál"
    lore: "Kde se objevíš?"
    permission: "aeterum.hades.portal"
    custom_id: 60018
    material: "SPLASH_POTION"
    color:
      red: 255
      green: 30
      blue: 50
    recipe:
      - AIR:GLASS_BOTTLE:AIR
      - OBSIDIAN:DRAGON_BREATH:OBSIDIAN
      - GHAST_TEAR:CRYING_OBSIDIAN:GHAST_TEAR
  ZOMBIE_HORSE_TAME:
    name: "Hádesův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.hades.horse_tame"
    custom_id: 60005
    material: "GOAT_HORN"
    recipe:
      - AIR:WITHER_ROSE:AIR
      - WITHER_ROSE:GOLDEN_APPLE:WITHER_ROSE
      - AIR:WITHER_ROSE:AIR
  ZOMBIE_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.hades.horse_ability"
  HADES_COMMAND:
    name: "Nightvision"
    permission: "aeterum.hades.command"
  HADES_GUI:
    name: "GUI"
    permission: "aeterum.hades.gui"
  FLYING_ITEM:
    name: "Nekonečná Raketka"
    lore: "Málo raketek? Použij toto."
    permission: "aeterum.hermes.flying_item"
    custom_id: 60019
    material: "STONE_SWORD"
    recipe:
      - REDSTONE:ENDER_PEARL:REDSTONE
      - IRON_INGOT:ELYTRA:IRON_INGOT
      - IRON_INGOT:REDSTONE:IRON_INGOT
  MESSENGER_PACK:
    name: "Poštovní Brašna"
    lore: "Bůh zpráv potřebuje pořádnou brašnu"
    permission: "aeterum.hermes.messenger_pack"
    custom_id: 60020
    material: "BUNDLE"
    recipe:
      - LEATHER:STRING:LEATHER
      - CHEST:GOLDEN_APPLE:CHEST
      - LEATHER:STRING:LEATHER
  SPEED_BOOTS:
    name: "Rychlé botky"
    lore: "Tyhle botky vypadají rychle. Nezakopni."
    permission: "aeterum.hermes.speed_boots"
    custom_id: 60021
    material: "IRON_BOOTS"
    recipe:
      - LEATHER:AIR:LEATHER
      - SUGAR:IRON_BOOTS:SUGAR
      - LEATHER:AIR:LEATHER
  SPEED_HORSE_TAME:
    name: "Hermesův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.hermes.horse_tame"
    custom_id: 60007
    material: "GOAT_HORN"
    recipe_potion: swiftness
    recipe:
      - AIR:POTION:AIR
      - POTION:GOLDEN_APPLE:POTION
      - AIR:AIR:AIR
  SPEED_HORSE_ABILITY:
    name: "Lektvar Rychlích Kopit"
    lore: "Sedni na svého koně, napij se a drž se"
    permission: "aeterum.hermes.horse_ability"
    custom_id: 60008
    material: "POTION"
    color:
      red: 193
      green: 193
      blue: 193
    recipe:
      - WHEAT:SUGAR:WHEAT
      - AIR:GLASS_BOTTLE:AIR
      - AIR:AIR:AIR
  HERMES_GUI:
    name: "GUI"
    permission: "aeterum.hermes.gui"
  SEA_HORSE_TAME:
    name: "Poseidonův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.poseidon.horse_tame"
    custom_id: 60009
    material: "GOAT_HORN"
    recipe:
      - AIR:NAUTILUS_SHELL:AIR
      - NAUTILUS_SHELL:GOLDEN_APPLE:NAUTILUS_SHELL
      - AIR:NAUTILUS_SHELL:AIR
  SEA_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.poseidon.horse_ability"
  WATER_BREATHING_CROWN:
    name: "Mořská Koruna"
    lore: "Pomáhá dýchat pod vodou."
    permission: "aeterum.poseidon.crown"
    custom_id: 60023
    material: "TURTLE_HELMET"
    recipe:
      - NAUTILUS_SHELL:NAUTILUS_SHELL:NAUTILUS_SHELL
      - NAUTILUS_SHELL:TURTLE_HELMET:NAUTILUS_SHELL
      - AIR:AIR:AIR
  BETTER_TRIDENT:
    name: "Královský Trojzubec"
    lore: "Zbraň hodná krále moří"
    permission: "aeterum.poseidon.trident"
    custom_id: 60022
    material: "TRIDENT"
    recipe:
      - AIR:HEART_OF_THE_SEA:AIR
      - NAUTILUS_SHELL:TRIDENT:NAUTILUS_SHELL
      - NAUTILUS_SHELL:BOOK:NAUTILUS_SHELL
  POSEIDON_COMMAND:
    name: "Dolphingrace"
    permission: "aeterum.poseidon.command"
  POSEIDON_GUI:
    name: "GUI"
    permission: "aeterum.poseidon.gui"
  PEGASUS_HORSE_TAME:
    name: "Diův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.zeus.horse_tame"
    custom_id: 60010
    material: "GOAT_HORN"
    recipe:
      - AIR:WIND_CHARGE:AIR
      - WIND_CHARGE:GOLDEN_APPLE:WIND_CHARGE
      - AIR:WIND_CHARGE:AIR
  PEGASUS_HORSE_ABILITY:
    name: "Lektvar Levitujících Kopit"
    lore: "Napij se když si na svém koni"
    permission: "aeterum.zeus.horse_ability"
    custom_id: 60011
    material: "POTION"
    color:
      red: 204
      green: 205
      blue: 208
    recipe:
      - AIR:FEATHER:AIR
      - FEATHER:GLASS_BOTTLE:FEATHER
      - AIR:FEATHER:AIR
  BREEDING_ITEM:
    name: "Afrodisiakum"
    lore: "Nakrm zvíře"
    permission: "aeterum.zeus.breeding_item"
    custom_id: 60024
    material: "SLIME_BALL"
    recipe:
      - AIR:CARROT:AIR
      - BEETROOT:SLIME_BALL:WHEAT
      - AIR:POTATO:AIR
  LIGHTNING_SPEAR:
    name: "Blesk"
    lore: "Zbraň hodná hrále Olympu"
    permission: "aeterum.zeus.lightning_spear"
    custom_id: 60025
    material: "TRIDENT"
    recipe:
      - IRON_INGOT:AIR:IRON_INGOT
      - STICK:TRIDENT:STICK
      - AIR:LIGHTNING_ROD:AIR
  WEATHER_CHANGER:
    name: "Lektvar Bouře"
    lore: "Moc slunečno? Tohle by mohlo být řešení"
    permission: "aeterum.zeus.weather_changer"
    custom_id: 60026
    material: "POTION"
    color:
      red: 165
      green: 161
      blue: 215
    recipe:
      - AIR:NETHER_STAR:AIR
      - DIAMOND:REDSTONE:DIAMOND
      - IRON_INGOT:BLAZE_ROD:IRON_INGOT
  ZEUS_GUI:
    name: "GUI"
    permission: "aeterum.zeus.gui"
  RANDOMIZER:
    name: "Lopatka"
    lore: "Položí náhodný block z hotbaru"
    permission: "aeterum.trowel.use"
    custom_id: 60015
    material: "IRON_SHOVEL"
    recipe:
      - BLAZE_POWDER:PHANTOM_MEMBRANE:BLAZE_POWDER
      - END_ROD:STICK:END_ROD
      - FEATHER:STICK:FEATHER