name: AeterumX
version: '${project.version}'
main: me.figgnus.aeterum.AeterumX
api-version: '1.21'
commands:
  nightvision:
    description: "Gives player nightvision"
    usage: /nightvision
  dolphingrace:
    description: "Gives player dolphin's grace"
    usage: /dolphingrace
  aeterum:
    description: "Contains all Aeterum commands"
    usage: /aeterum